apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector: #resposavel por filtros todos os pods incomporados neste serviço
    app: goserver
  type: ClusterIP
  ports:
    - name: goserver-service
      port: 8080
      protocol: TCP
